Do not ask Dirk for help with my files. Just drop them into inventory and paste over Dirk's original PNG.

If you have a script handling weed effects and rolling joints, making brownies/gummies, you will need to make a copy of the name in your scripts.

jim-g

Some weed images I've made for dirks weed script but you can use them anywhere. I will be adding more to this, even making new plant props—all for free.

If you would like the script that works with all the names, [WEED-GROWING] go check out Dirk's Discord Where can you purchase the script. :https://discord.gg/dirkscripts

info: weed leaf / weed seed / weed trimmed_bud / weed untrimmed_bud / weed bags / weed gummy / weed joints / weed brownies /


iteams :::

    -- buds
    ['acapulcogold_trimmed_bud']     = {['name'] = 'acapulcogold_trimmed_bud',     ['label'] = 'acapulcogold_trimmed_bud',       ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'acapulcogold_trimmed_bud.png',         ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['colombiangold_trimmed_bud']    = {['name'] = 'colombiangold_trimmed_bud',    ['label'] = 'colombiangold_trimmed_bud',      ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'colombiangold_trimmed_bud.png',        ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['dosidos_trimmed_bud']          = {['name'] = 'dosidos_trimmed_bud',          ['label'] = 'dosidos_trimmed_bud',            ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'dosidos_trimmed_bud.png',              ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gelato41_trimmed_bud']         = {['name'] = 'gelato41_trimmed_bud',         ['label'] = 'gelato41_trimmed_bud',           ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gelato41_trimmed_bud.png',             ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['lemonskunk_trimmed_bud']       = {['name'] = 'lemonskunk_trimmed_bud',       ['label'] = 'lemonskunk_trimmed_bud',         ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'lemonskunk_trimmed_bud.png',           ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['northernlights_trimmed_bud']   = {['name'] = 'northernlights_trimmed_bud',   ['label'] = 'northernlights_trimmed_bud',     ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'northernlights_trimmed_bud.png',       ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['ogkush_trimmed_bud']           = {['name'] = 'ogkush_trimmed_bud',           ['label'] = 'ogkush_trimmed_bud',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'ogkush_trimmed_bud.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['pureafghani_trimmed_bud']      = {['name'] = 'pureafghani_trimmed_bud',      ['label'] = 'pureafghani_trimmed_bud',        ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'pureafghani_trimmed_bud.png',          ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['rainbowbelts_trimmed_bud']     = {['name'] = 'rainbowbelts_trimmed_bud',     ['label'] = 'rainbowbelts_trimmed_bud',       ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'rainbowbelts_trimmed_bud.png',         ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['skunk1_trimmed_bud']           = {['name'] = 'skunk1_trimmed_bud',           ['label'] = 'skunk1_trimmed_bud',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'skunk1_trimmed_bud.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},

    -- crop 
    ['acapulcogold_untrimmed_bud']   = {['name'] = 'acapulcogold_untrimmed_bud',   ['label'] = 'acapulcogold_untrimmed_bud',     ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'acapulcogold_untrimmed_bud.png',       ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['colombiangold_untrimmed_bud']  = {['name'] = 'colombiangold_untrimmed_bud',  ['label'] = 'colombiangold_untrimmed_bud',    ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'colombiangold_untrimmed_bud.png',      ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['dosidos_untrimmed_bud']        = {['name'] = 'dosidos_untrimmed_bud',        ['label'] = 'dosidos_untrimmed_bud',          ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'dosidos_untrimmed_bud.png',            ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gelato41_untrimmed_bud']       = {['name'] = 'gelato41_untrimmed_bud',       ['label'] = 'gelato41_untrimmed_bud',         ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gelato41_untrimmed_bud.png',           ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['lemonskunk_untrimmed_bud']     = {['name'] = 'lemonskunk_untrimmed_bud',     ['label'] = 'lemonskunk_untrimmed_bud',       ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'lemonskunk_untrimmed_bud.png',         ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['northernlights_untrimmed_bud'] = {['name'] = 'northernlights_untrimmed_bud', ['label'] = 'northernlights_untrimmed_bud',   ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'northernlights_untrimmed_bud.png',     ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['ogkush_untrimmed_bud']         = {['name'] = 'ogkush_untrimmed_bud',         ['label'] = 'ogkush_untrimmed_bud',           ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'ogkush_untrimmed_bud.png',             ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['pureafghani_untrimmed_bud']    = {['name'] = 'pureafghani_untrimmed_bud',    ['label'] = 'pureafghani_untrimmed_bud',      ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'pureafghani_untrimmed_bud.png',        ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['rainbowbelts_untrimmed_bud']   = {['name'] = 'rainbowbelts_untrimmed_bud',   ['label'] = 'rainbowbelts_untrimmed_bud',     ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'rainbowbelts_untrimmed_bud.png',       ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['skunk1_untrimmed_bud']         = {['name'] = 'skunk1_untrimmed_bud',         ['label'] = 'skunk1_untrimmed_bud',           ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'skunk1_untrimmed_bud.png',             ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},

    -- leafs 
    ['acapulcogold_leaf']            = {['name'] = 'acapulcogold_leaf',            ['label'] = 'acapulcogold_leaf',              ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'acapulcogold_leaf.png',                ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['colombiangold_leaf']           = {['name'] = 'colombiangold_leaf',           ['label'] = 'colombiangold_leaf',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'colombiangold_leaf.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['dosidos_leaf']                 = {['name'] = 'dosidos_leaf',                 ['label'] = 'dosidos_leaf',                   ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'dosidos_leaf.png',                     ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gelato41_leaf']                = {['name'] = 'gelato41_leaf',                ['label'] = 'gelato41_leaf',                  ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gelato41_leaf.png',                    ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['lemonskunk_leaf']              = {['name'] = 'lemonskunk_leaf',              ['label'] = 'lemonskunk_leaf',                ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'lemonskunk_leaf.png',                  ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['northernlights_leaf']          = {['name'] = 'northernlights_leaf',          ['label'] = 'northernlights_leaf',            ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'northernlights_leaf.png',              ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['ogkush_leaf']                  = {['name'] = 'ogkush_leaf',                  ['label'] = 'ogkush_leaf',                    ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'ogkush_leaf.png',                      ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['pureafghani_leaf']             = {['name'] = 'pureafghani_leaf',             ['label'] = 'pureafghani_leaf',               ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'pureafghani_leaf.png',                 ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['rainbowbelts_leaf']            = {['name'] = 'rainbowbelts_leaf',            ['label'] = 'rainbowbelts_leaf',              ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'rainbowbelts_leaf.png',                ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['skunk1_leaf']                  = {['name'] = 'skunk1_leaf',                  ['label'] = 'skunk1_leaf',                    ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'skunk1_leaf.png',                      ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},

    -- joints 
    ['acapulcogold_joint']           = {['name'] = 'acapulcogold_joint',           ['label'] = 'acapulcogold_joint',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'acapulcogold_joint.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['colombiangold_joint']          = {['name'] = 'colombiangold_joint',          ['label'] = 'colombiangold_joint',            ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'colombiangold_joint.png',              ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['dosidos_joint']                = {['name'] = 'dosidos_joint',                ['label'] = 'dosidos_joint',                  ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'dosidos_joint.png',                    ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gelato41_joint']               = {['name'] = 'gelato41_joint',               ['label'] = 'gelato41_joint',                 ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gelato41_joint.png',                   ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['lemonskunk_joint']             = {['name'] = 'lemonskunk_joint',             ['label'] = 'lemonskunk_joint',               ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'lemonskunk_joint.png',                 ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['northernlights_joint']         = {['name'] = 'northernlights_joint',         ['label'] = 'northernlights_joint',           ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'northernlights_joint.png',             ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['ogkush_joint']                 = {['name'] = 'ogkush_joint',                 ['label'] = 'ogkush_joint',                   ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'ogkush_joint.png',                     ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['pureafghani_joint']            = {['name'] = 'pureafghani_joint',            ['label'] = 'pureafghani_joint',              ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'pureafghani_joint.png',                ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['rainbowbelts_joint']           = {['name'] = 'rainbowbelts_joint',           ['label'] = 'rainbowbelts_joint',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'rainbowbelts_joint.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['skunk1_joint']                 = {['name'] = 'skunk1_joint',                 ['label'] = 'skunk1_joint',                   ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'skunk1_joint.png',                     ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},

    -- gummys
    ['gummy_acapulcogold']           = {['name'] = 'gummy_acapulcogold',           ['label'] = 'gummy_acapulcogold',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_acapulcogold.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_colombiangold']          = {['name'] = 'gummy_colombiangold',          ['label'] = 'gummy_colombiangold',            ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_colombiangold.png',              ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_dosidos']                = {['name'] = 'gummy_dosidos',                ['label'] = 'gummy_dosidos',                  ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_dosidos.png',                    ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_gelato41']               = {['name'] = 'gummy_gelato41',               ['label'] = 'gummy_gelato41',                 ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_gelato41.png',                   ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_lemonskunk']             = {['name'] = 'gummy_lemonskunk',             ['label'] = 'gummy_lemonskunk',               ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_lemonskunk.png',                 ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_northernlights']         = {['name'] = 'gummy_northernlights',         ['label'] = 'gummy_northernlights',           ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_northernlights.png',             ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_ogkush']                 = {['name'] = 'gummy_ogkush',                 ['label'] = 'gummy_ogkush',                   ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_ogkush.png',                     ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_pureafghani']            = {['name'] = 'gummy_pureafghani',            ['label'] = 'gummy_pureafghani',              ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_pureafghani.png',                ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_rainbowbelts']           = {['name'] = 'gummy_rainbowbelts',           ['label'] = 'gummy_rainbowbelts',             ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_rainbowbelts.png',               ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},
    ['gummy_skunk1']                 = {['name'] = 'gummy_skunk1',                 ['label'] = 'gummy_skunk1',                   ['weight'] = 001,          ['type'] = 'item',         ['image'] = 'gummy_skunk1.png',                     ['unique'] = false,         ['useable'] = true,     ['shouldClose'] = false,      ['combinable'] = nil,   ['description'] = 'A weed bag with 2g White Widow'},

    -- brownies
    ['brownie_acapulcogold'] 	     = {['name'] = 'brownie_acapulcogold', 		   ['label'] = 'brownie acapulcogold', 	         ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_acapulcogold.png', 	           ['unique'] = false, 	       ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'acapulcogold brownie'},
    ['brownie_colombiangold'] 	     = {['name'] = 'brownie_colombiangold', 	   ['label'] = 'brownie colombiangold', 	     ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_colombiangold.png', 	           ['unique'] = false, 	       ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'colombiangold brownie'},
    ['brownie_dosidos'] 		     = {['name'] = 'brownie_dosidos', 			   ['label'] = 'brownie dosidos', 			     ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_dosidos.png', 		               ['unique'] = false, 	       ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'dosidos brownie'},
    ['brownie_gelato41'] 		     = {['name'] = 'brownie_gelato41', 			   ['label'] = 'brownie gelato41', 		         ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_gelato41.png', 		           ['unique'] = false, 	       ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'gelato41 brownie'},
    ['brownie_lemonskunk'] 		     = {['name'] = 'brownie_lemonskunk', 		   ['label'] = 'brownie lemonskunk', 	       	 ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_lemonskunk.png', 		           ['unique'] = false, 	       ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'lemonskunk brownie'},
    ['brownie_northernlights'] 	     = {['name'] = 'brownie_northernlights', 	   ['label'] = 'brownie northernlights', 	     ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_northernlights.png', 	           ['unique'] = false,         ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'northernlights brownie'},
    ['brownie_ogkush'] 			     = {['name'] = 'brownie_ogkush', 			   ['label'] = 'brownie ogkush', 			     ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_ogkush.png', 		               ['unique'] = false,         ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'ogkush brownie'},
    ['brownie_pureafghani'] 	     = {['name'] = 'brownie_pureafghani', 		   ['label'] = 'brownie pureafghani', 	         ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_pureafghani.png', 		           ['unique'] = false,         ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'pureafghani brownie'},
    ['brownie_rainbowbelts'] 	     = {['name'] = 'brownie_rainbowbelts', 		   ['label'] = 'brownie rainbowbelts', 	         ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_rainbowbelts.png', 	           ['unique'] = false,         ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'rainbowbelts brownie'},
    ['brownie_skunk1'] 			     = {['name'] = 'brownie_skunk1', 			   ['label'] = 'brownie skunk1', 			     ['weight'] = 380, 		    ['type'] = 'item', 		['image'] = 'brownie_skunk1.png', 		               ['unique'] = false,         ['useable'] = true, 	   ['shouldClose'] = true,       ['combinable'] = nil,   ['description'] = 'skunk1 brownie'},
